### ISSUE TITLE
how can we use pip install this

### ISSUE THREAD

**Issue by wanghaisheng** [ToucanToco/fastexcel#155]

**Comment by lukapeschke** [comment]
You can use `pip install fastexcel`. If you're encountering issues, please provide your platform, OS and python version :slightly_smiling_face:

**Comment by wanghaisheng** [comment]
actuallyy 


$ pip install fastexcel
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement fastexcel (from versions: none)
ERROR: No matching distribution found for fastexcel

**Comment by lukapeschke** [comment]
It looks like you are on custom pypi mirrors: 

>  Looking in indexes: https://mirrors.aliyun.com/pypi/simple/

There are two solutions here:
* Use the official package index: files.pythonhosted.org
* Ask your mirror admins to add the `fastexcel` wheels to your mirror

**Comment by lukapeschke** [comment]
@wanghaisheng I'm closing this for now, feel free to reopen the issue if installing from the official PyPI mirrors fails

**Comment by abcfy2** [comment]
Might be the same issue as: https://github.com/ToucanToco/fastexcel/issues/273
