### ISSUE TITLE
Be able to select a subset of columns

### ISSUE THREAD

**Issue by PrettyWood** [ToucanToco/fastexcel#172]
We should be able to read an excel dataframe that starts at column `B` for example
see `usecols` of https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

**Comment by lukapeschke** [comment]
@PrettyWood have you already have a look at this ? Otherwise, I'd take it :slightly_smiling_face:

**Comment by PrettyWood** [comment]
Go ahead! I have way too much work already :D You can take all the issues! ;)

**Comment by lukapeschke** [comment]
Haha I'll try :wink:
