### ISSUE TITLE
request: arm64 linux wheels

### ISSUE THREAD

**Issue by jwhitaker-gridcog** [ToucanToco/fastexcel#193]
hey guys, any chance of publishing wheels for linux/arm64? the lack of an sdist for this means we're kinda stuck without it.
Is this on the roadmap anyway or would you appreciate a PR adding it to your release action?

Thanks for maintaining this!

**Comment by PrettyWood** [comment]
We just switched to abi3 wheel. You can try on `main` and see if this works well

**Comment by lukapeschke** [comment]
@jwhitaker-gridcog wheels for linux/arm64 are available starting with v0.10.1 :) https://pypi.org/project/fastexcel/0.10.1/#files
