### ISSUE TITLE
When using fastexcel to read Excel files, empty rows are automatically ignored by default

### ISSUE THREAD

**Issue by karond-is-me** [ToucanToco/fastexcel#200]
When using fastexcel to read Excel files, empty rows are automatically ignored by default, which can create significant issues. It would be beneficial to provide an optional parameter to adjust this behavior.

**Comment by wikiped** [comment]
It is somewhat unlcear if the issue has been closed becase it has been fixed or for some other reason, while the issue still exists (version `0.9.1`)
