### ISSUE TITLE
Support for Reading Excel Tables

### ISSUE THREAD

**Issue by aersam** [ToucanToco/fastexcel#204]
From my experience it's usually much safer to load data from an excel table than from a sheet. would be nice if one could get the table names per sheet and get the table data as arrow/pandas like with the sheets

**Comment by lukapeschke** [comment]
Hi @aersam , could you please provide a bit more details on what you have in mind ? And maybe provide a few examples on how that parameter is passed in other libraries (for example pandas) ? A file with the issue you are encountering would also be great

**Comment by aersam** [comment]
Hi there!
Here's a sample file:  [tables.xlsx](https://github.com/ToucanToco/fastexcel/files/14703008/tables.xlsx)
I'd like to pass the table_name instead of sheet_name, table name's are unique within an excel workbook as well:

![image](https://github.com/ToucanToco/fastexcel/assets/5270024/b54cd319-4e14-4bda-9999-5cd1b6edeab8)

**Comment by lukapeschke** [comment]
Thanks! This seems to be doable through calamine's APIs (https://docs.rs/calamine/latest/calamine/struct.Xlsx.html#method.table_by_name) but will require quite some work, so I don't know when/if we will ship it... We might pritoritize this if a lot of people ask for this feature :slightly_smiling_face:

**Comment by alexander-beedie** [comment]
> Thanks! This seems to be doable through calamine's APIs (https://docs.rs/calamine/latest/calamine/struct.Xlsx.html#method.table_by_name) but will require quite some work, so I don't know when/if we will ship it... We might pritoritize this if a lot of people ask for this feature 🙂

As a minor FYI, we always write "real" Excel table objects from Polars' `write_excel` method as they are generally considered quite useful, given how freeform Excel can otherwise be ;)

**Comment by alexander-beedie** [comment]
> @alexander-beedie ah good to know, thanks! How do you handle tables on read ? Is there a parameter to read a specific table ?

At the moment I don't, heh 😎  However, I was thinking about adding a `table_name` parameter, as one of our other engines (openpyxl) also supports reading table objects. If we could get an equivalent capability for fastexcel that would be really nice 👌
