### ISSUE TITLE
"use_columns" keyword argument not recognized by `load_sheet`.

### ISSUE THREAD

**Issue by smallzhan** [ToucanToco/fastexcel#207]
According to https://fastexcel.toucantoco.dev/fastexcel.html#ExcelReader.load_sheet,  there is a "use_columns" keyword
 argument, but in fact the keyword is not recognized.

```
>>> import fastexcel
>>> te = fastexcel.read_excel("1.xlsx")
>>> te
ExcelReader<1.xlsx>
>>> te.load_sheet(0, use_columns="A:E")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ExcelReader.load_sheet() got an unexpected keyword argument 'use_columns'
>>>
```

**Comment by PrettyWood** [comment]
Hi @smallzhan 
The doc is on `master`. The `use_columns` is coming up soon in [v0.10.0](https://github.com/ToucanToco/fastexcel/milestone/3?closed=1)
We will try to release it in a couple of days

**Comment by lukapeschke** [comment]
Closing this since v0.10.0 has been released :slightly_smiling_face: Feel free to open another issue if you still run into trouble
