### ISSUE TITLE
Create conda package for install with `conda`/`mamba`

### ISSUE THREAD

**Issue by dangotbanned** [ToucanToco/fastexcel#219]
I was hoping to benchmark `fastexcel` vs `xlsx2csv` to determine if I'd benefit from the performance in the context of `polars`.

I haven't found any discussion mentioning `conda-forge`, but they have a guide for [contributing packages](https://conda-forge.org/docs/maintainer/adding_pkgs/).

Would this be something you could add to your CI?

Edit:
Since `polars` is similar in the `python`/`rust` overlap, the [polars-feedstock](https://github.com/conda-forge/polars-feedstock) might be a helpful reference.

**Comment by ba05** [comment]
Looks like someone is already working this?: https://github.com/conda-forge/staged-recipes/pull/26876

**Comment by arnabanimesh** [comment]
[fastexcel](https://anaconda.org/conda-forge/fastexcel) conda-forge package is finally up. :)

**Comment by ba05** [comment]
https://anaconda.org/conda-forge/fastexcel

**Comment by dangotbanned** [comment]
> [fastexcel](https://anaconda.org/conda-forge/fastexcel) conda-forge package is finally up. :)

Thanks @arnabanimesh
