### ISSUE TITLE
load_sheet_by_name raises generic CalamineError instead of SheetNotFoundError

### ISSUE THREAD

**Issue by sean-moore3** [ToucanToco/fastexcel#221]
Hi,

While loading a sheet from a reader, if a missing sheet name is provided a generic `CalamineError` is raised instead of the more specific `SheetNotFoundError`.

My use case is:

```python
sheets = []
for reader in readers:
    try:
        sheet = reader.load_sheet_by_name("sheet_name")
    except SheetNotFoundError:
        continue
    # Do some other stuff with sheet before appending to list.
```

**Comment by PrettyWood** [comment]
Hi @sean-moore3 
Thanks for reporting this is indeed a bug. I'll push a fix
