### ISSUE TITLE
header_row does not work as expected if there are blank rows

### ISSUE THREAD

**Issue by noctuid** [ToucanToco/fastexcel#233]
If I put expect the header on e.g. row index 15, but there are blank rows (at least at the beginning of the sheet), I cannot do `header_row=15`.  It looks like they are ignored, so I have to put in a lower index.

**Comment by PrettyWood** [comment]
Hello!
can you please provide an excel sheet example?

**Comment by noctuid** [comment]
I will try to create a basic sheet to reproduce. It seems the issue is not actually with blank rows, but there is some other I am having to put in a much lower index than I expect.

**Comment by noctuid** [comment]
It looks like it does have to do with empty rows in some case.. not exactly clear to me, but it's very easy to reproduce with this file:

[TestFastExcelRead.xlsx](https://github.com/ToucanToco/fastexcel/files/15015950/TestFastExcelRead.xlsx)

I have the header row on row 8 (0-based; 9 in excel) but have to specify it as 6. You can also remove that "Note 1" cell to change things.

```python
def test_row_issue():
    reader = read_excel("...TestFastExcelRead.xlsx")
    ws = reader.load_sheet("Sheet1", header_row=6)
    df = ws.to_pandas()
```

**Comment by PrettyWood** [comment]
I'll try to dig into it this weekend

**Comment by lukapeschke** [comment]
seem related to #209

**Comment by PrettyWood** [comment]
see This requires changes on calamine side. I will try to open a PR soon. Since 0.11 has some nice improvements, we don't want to postpone it even more for that
