### ISSUE TITLE
Add a note to the `skip_rows` and `header_row` parameter description that rows before header_row are automatically skipped

### ISSUE THREAD

**Issue by deanm0000** [ToucanToco/fastexcel#255]
This one feels a little silly but it took me a few minutes to realize that if I do `header_row=5` that I don't also have to do `skip_rows=6`. I don't have any suggestion to change the behavior just the documentation.

Concretely I think the skip_rows should say:

>Specifies how many rows should be skipped after the `header_row`. 
Any rows before the `header_row` are automatically skipped.
If `header_row` is `None`, it skips the number of rows from the
start of the sheet.

and then the `header_row` should be

> The index of the row containing the column labels, default index is 0.
If `None`, the sheet does not have any column labels.
Any rows before the `header_row` will automatically be skipped.

**Comment by PrettyWood** [comment]
You're right! PR welcome to improve the doc :)
