### ISSUE TITLE
Strange failure to determine `string` dtype column in ODS sheet/file

### ISSUE THREAD

**Issue by alexander-beedie** [ToucanToco/fastexcel#275]
Attached two visually-identical files below that can be used to reproduce the issue. Both appear to contain identical column data, but one fails to load while the other succeeds.

![Screenshot 2024-08-07 at 12 08 56](https://github.com/user-attachments/assets/9e843ca0-fa91-4787-b286-831e19d37139)

⬇️ [success.ods](https://github.com/user-attachments/files/16520816/success.ods)
⬇️ [failure.ods](https://github.com/user-attachments/files/16520818/failure.ods)

### Example:
```python
import fastexcel as xl

xl.read_excel("success.ods").load_sheet(0)
# ExcelSheet<Test>

xl.read_excel("failure.ods").load_sheet(0)
# CannotRetrieveCellDataError: cannot retrieve cell data at (8, 0)
# Context:
#     0: could not determine dtype for column StringCol
```

**Comment by archqt** [comment]
It still doesn't work, i have now polars 1.7.1 / fastexcel 0.11.5

**Comment by PrettyWood** [comment]
calamine 0.26 has been released and added in fastexcel
Release 0.12.0 of fastexcel will fix this issue. I plan to release it this week

**Comment by alexander-beedie** [comment]
> Release 0.12.0 of fastexcel will fix this issue. I plan to release it this week

Nice! Thanks for this one :)

**Comment by PrettyWood** [comment]
v0.12.0 is out
