### ISSUE TITLE
Upload source distribution to PyPi

### ISSUE THREAD

**Issue by MarcelBeining** [ToucanToco/fastexcel#283]
Hi there,
I need to use fastexcel on a raspberry PI, where I cannot use the precompiled wheels of fastexcel on PyPi.
There is piwheels.org, which serves as wheel source for raspberry PI ARM architecture, but they only can serve an ARM precompiled fastexcel wheel if the source distribution (tar.gz file) is available on PyPi. Would you mind uploading that, too on PyPI at each release?

In the meantime I clone and build the distribution by myself but this is cumbersome.

Thanks :-)

**Comment by lukapeschke** [comment]
Sure, should be doable! :) I'll look into it

**Comment by lukapeschke** [comment]
@MarcelBeining could you please try to install [this artifact](https://github.com/ToucanToco/fastexcel/actions/runs/10811150459/artifacts/1919235896) ? (Note that you'll have to unzip it to access the source dist). If it works for you, we can enable source distribution publishing :)
