### ISSUE TITLE
Provide functions returning `polars.DataFrame`

### ISSUE THREAD

**Issue by lukapeschke** [ToucanToco/fastexcel#3]
These should be implemented in rust directly. It'd allow us to prevent the `arrow` -> `PyBytes` -> `arrow` -> `pandas` memory overhead

**Comment by jGundermann** [comment]
Like pandas polars should maybe be a extra.

**Comment by lukapeschke** [comment]
> Like pandas polars should maybe be a extra.

Yup that's the plan :) Forgot to specify it in the issue, thank you!

**Comment by jGundermann** [comment]
done with #87
