### ISSUE TITLE
Refactoring the arrow array's creations

### ISSUE THREAD

**Issue by jGundermann** [ToucanToco/fastexcel#31]
https://github.com/ToucanToco/fastexcel/blob/dfe46bd3cd88b87813cb3eef475fea1b8e8f9b8a/src/types/excelsheet.rs#L48-L80

Maybe we could change this :
- Maybe add a trait
- Maybe a closure
- Maybe something else...

**Comment by lukapeschke** [comment]
Just a note: All functions have the same pattern: `.and_then(|cell| cell.get_x())` . But `create_datetime_array` needs an extra transformation (`.to_milliseconds`). When proposing a design, keep in mind that we might need that we night need extra transformation for types that will be added in the future.
